name: The Angry Muffin Blog
favicon: null
layout_spectrum: 0.6791855653282255
typography_spectrum: 0.7258839146234095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7285026300232857
  lightness: 0.06129552307538688
  saturation: 0.34127698093652725
  rhythmicContrast: 0.9854659901466221
purpose: []
